services:
  db:
    image: postgres:16.1
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
      - PGOPTIONS=-c log_statement=all -c log_min_messages=debug1 -c log_connections=on -c log_disconnections=on
    healthcheck:
      test: pg_isready -q -d shareit -U dbuser
      timeout: 5s
      interval: 5s
      retries: 10
    networks:
      - db-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: northernnikolay@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 12345
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "8081:80"
    networks:
      - db-network
    restart: unless-stopped

volumes:
  postgres-data:
  pgadmin-data:
networks:
  db-network:
    driver: bridge